### PR TITLE
Update font types

### LINKED ISSUE #77: Update font media types
The [`font` top-level media type](https://tools.ietf.org/html/rfc8081) has been registered, so the new media types for font files are as follows:

| Font format | Media type |
|:---|:---|
| `collection` | `font/collection` |
| `otf` | `font/otf` |
| `sfnt` | `font/sfnt` |
| `ttf` | `font/ttf` |
| `woff` |	`font/woff` | 	
| `woff2` | `font/woff2` |

See also: https://www.iana.org/assignments/media-types/media-types.xhtml#font

---

@dougwilson I did run the `fetch-iana` script but it doesn't seem to get these updates. Let me know if you are open to updating `custom.json`.

### PR DESCRIPTION
**Pull request by alrra**
Ref:
* https://www.iana.org/assignments/media-types/media-types.xhtml#font
* https://tools.ietf.org/html/rfc8081
    
Fix: #77

----

@dougwilson Let me know if you want anything changed. Thanks!

### CODE REVIEW

**Comment by alrra** [comment]
@dougwilson If and when you have time, can you look over this? Thanks!

**Comment by dougwilson** [comment]
Yea, sorry, don't know why I didn't get an email when it was opened.

**Comment by alrra** [comment]
@dougwilson Friendly ping. 👋

**Comment by alrra** [comment]
@dougwilson Friendly ping. 👋

**Comment by dougwilson** [comment]
Sorry, didn't get it before I left on a trip. Back now and getting this published today for everyone 🎉

**Comment by alrra** [comment]
> getting this published today for everyone 

Thanks!

**Pull request closed without merging**
