### PR TITLE
Update custom-types.json

### PR DESCRIPTION
**Pull request by billymoon**
add type for http://slim-lang.com/

### CODE REVIEW

**Comment by dougwilson** [comment]
Thanks, merged!

**Comment by billymoon** [comment]
@dougwilson and idea when this change will make it into a release?

**Comment by dougwilson** [comment]
Hi @billymoon, sorry it took a bit to get back to you due to unforeseen circumstances. I'm going to release a new version with this change today for you.

**Comment by billymoon** [comment]
@dougwilson thanks!

**Pull request closed without merging**
