### PR TITLE
Added one more BMP mime type

### PR DESCRIPTION
**Pull request by mikhail-guru**

### CODE REVIEW

**Comment by jonathanong** [comment]
do you have a sourcE?

**Comment by mikhailguru** [comment]
@jonathanong  Source was a libmime library, i.e. if you will take BMP file (at least which I have) and do `file this_file.bmp` command you get this source type. I've found such file on http://atheos.cx/screenshots/shot7.php3. Russian Wikipedia (http://ru.wikipedia.org/wiki/BMP) tells us that such mimetype exists, and `file` command also detects it as "image/x-ms-bmp".

**Comment by dougwilson** [comment]
I agree that I have seem `image/x-ms-bmp` around in places.

**Comment by jonathanong** [comment]
hmmm i swore we had a `sources.md` file or something. oh well

**Comment by jonathanong** [comment]
oh. https://github.com/jshttp/mime-db/issues/6

**Comment by dougwilson** [comment]
For now we should be adding a `sources` property to the object with an array of strings defining source(s).

**Pull request closed without merging**
