### PR TITLE
add "application/x-ns-proxy-autoconfig"

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Ref:
 * https://web.archive.org/web/20070602031929/http://wp.netscape.com/eng/mozilla/2.0/relnotes/demo/proxy-live.html
 * https://en.wikipedia.org/wiki/Proxy_auto-config#The_PAC_File

### CODE REVIEW

**Comment by dougwilson** [comment]
Oh man, I remember pac files :)

**Comment by PeterDaveHello** [comment]
PAC is really useful in the network of enterprise or school (if they have there own proxy)!

**Comment by PeterDaveHello** [comment]
Cool, what's the difference merge on GitHub or cherry-pick it in the case?

**Comment by dougwilson** [comment]
Main differences are I can keep the history linear and do any necessary minor fixes without needing to burden the person who made the PR with petty things like style :)

**Comment by PeterDaveHello** [comment]
okay, great!

**Comment by dougwilson** [comment]
Published in version 1.10.0!

**Comment by PeterDaveHello** [comment]
:+1:

**Pull request closed without merging**
