### PR TITLE
Add `application/manifest+json` and update

### PR DESCRIPTION
**Pull request by alrra**
* Add `application/manifest+json`
   * https://w3c.github.io/manifest/#h-media-type-registration
   * https://github.com/w3c/manifest/issues/346
* Update

### CODE REVIEW

**Comment by jonathanong** [comment]
@dougwilson this looks good to me. wanna release?

**Comment by dougwilson** [comment]
I was waiting for IANA to update their registry, since this type was submitted so we didn't have to have a custom entry for it.

**Comment by jonathanong** [comment]
ok cool!

**Comment by dougwilson** [comment]
I was thinking if it's not in there by Friday then I'll just accept this PR and release :)

**Comment by dougwilson** [comment]
@alrra sorry for the slowness. Added it and it'll be published soon :)

**Comment by alrra** [comment]
> sorry for the slowness.

@dougwilson No problem at all. Thanks for merging! :)

**Pull request closed without merging**
