### PR TITLE
Add processing mime type

### PR DESCRIPTION
**Pull request by fmvilas**
Hi! I realised that Processing IDE extension is not in the database and I would like to add it.

Hope it helps!
Cheers!

### CODE REVIEW

**Comment by dougwilson** [comment]
Looks good, thank you!

**Comment by fmvilas** [comment]
You're welcome sir!

**Comment by fmvilas** [comment]
Hi again!

Can you please publish the changes to npm? :pray: I'm using this package through mime-types.

Thanks!

**Comment by dougwilson** [comment]
Sorry, published as 1.14.0! `mime-types` will be updated shortly.

**Comment by fmvilas** [comment]
Many thanks! :blush:

**Pull request closed without merging**
