### PR TITLE
Fix pin versions nyc version for testing on old versions of node <= 9

### LINKED ISSUE #317: Broken tests for Node@8 and Node@9
Seems like the current master branch have some broken tests when running Node@8 and Node@9. @UlisesGascon notice that when running my changes for PR https://github.com/jshttp/mime-db/pull/316

I can not provide a failed build because the workflow is waiting for approval
Screenshot 2024-03-26 at 09 48 29

But I can see the ci-test action failing in my forked repo
https://github.com/carpasse/mime-db/actions/runs/8418349804/job/23048681716

Similar error in both cases: https://github.com/jshttp/mime-types/actions/runs/8278038868/job/22655381584#step:10:15, here is an screenshot in case that you can't access to the logs:
Screenshot 2024-03-26 at 09 49 59

### PR DESCRIPTION
**Pull request by carpasse**
Closes #317
Same fix as jshttp/http-errors#109

### CODE REVIEW

**Comment by carpasse** [comment]
Removed Node.js v0.6 because GH fails to install it. I've checked the [ci-tests action in http-errors](https://github.com/jshttp/http-errors/blob/master/.github/workflows/ci.yml#L35) and it is not there probably because of similar reasons.

Screenshot 2024-03-26 at 10 06 08

**Comment by carpasse** [comment]
Node 0.6 run was probably canceled because the other builds failed. I will add it back and test.

**Comment by carpasse** [comment]
The build doesn't seem to finish after adding back node version 0.6
I had to cancel it after 8 min https://github.com/carpasse/mime-db/actions/runs/8433679841/job/23095235917
Screenshot 2024-03-26 at 10 38 59

@dougwilson @UlisesGascon should I remove node.js version 0.6 from the ci-tests? It will be in sync with [http-errors ci-tests.yml action](https://github.com/jshttp/http-errors/blob/master/.github/workflows/ci.yml#L35)

**Review by UlisesGascon — APPROVED** [review]
@carpasse Awesome work!

 :clap: :clap: CI is green again! https://github.com/jshttp/mime-db/actions/runs/8433680265

**Pull request merged**
