### PR TITLE
Update WebAssembly module type reference link

### PR DESCRIPTION
**Pull request by LeoColomb**

### CODE REVIEW

**Comment by dougwilson** [comment]
The original repo is deleted, so it's no longer mergable. Feel free to re-open the PR if you're interested!

**Comment by LeoColomb** [comment]
What do you mean? My fork?

**Comment by dougwilson** [comment]
Yea, I just tried to merge and I got the error message

> Sorry, this diff is unavailable.

And above, I see 

image

It seems to think your fork no longer exists, so there isn't a source to merge from.

**Comment by LeoColomb** [comment]
Really strange! Do you use a custom tool? GitHub always create a new git head in the target repo ([something like `pull/119/head`](https://help.github.com/articles/checking-out-pull-requests-locally/)), so it should not be a problem... and it's not the first time I delete my fork before a merge, never got a problem. 🤔

**Comment by dougwilson** [comment]
I was just using the GitHub GUI. Even the reopen button is disabled and the only thing I can do on this PR is comment:

image

**Comment by dougwilson** [comment]
Thanks for that article, though, because I was able to pull the commit down locally using `git fetch origin pull/119/head:pr-119`, so I'll push that up to `master` for you 👍

**Comment by dougwilson** [comment]
Rebased onto `master`: 1bffda3212029acbb16ccc38d3affc090efd397c

**Pull request closed without merging**
