### PR TITLE
Added new Microsoft appinstaller types

### PR DESCRIPTION
**Pull request by paulober**
See https://learn.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web for more details

### CODE REVIEW

**Review by dougwilson — CHANGES_REQUESTED** [review]
Hi @paulober thank you for this. This looks good, but needs minor tweaks. I tried to fix it for you, but I don't have permission to push to your fork. You can either enable us to push the fixes to your pull request following https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork or I need you to add a `sources` to each of those entries in `custom-types.json` referencing the link you provided and run `npm run build`.

**Comment by paulober** [comment]
@dougwilson Fixed the changes you requested...

**Comment by dougwilson** [comment]
Awesome, thanks @paulober ! It looks like you may have forgot to run `npm run build` still, and I tried to fix that for you, but you didn't add permission for me to push, so I just need you to do one of those, please 🙏

**Comment by paulober** [comment]
@dougwilson Sorry forgot about that. Is fixed...

**Review by dougwilson — APPROVED** [review]
Thank you so much and sorry for the delay in circling back to this!

**Pull request merged**
