### PR TITLE
Add SymWriter document and environment

### PR DESCRIPTION
**Pull request by leifcr**
Add extensions from SymWriter software (http://www.widgit.com/symwriter)

### CODE REVIEW

**Comment by dougwilson** [comment]
Awesome, thanks! Can you find us a web page somewhere that spells out these MIME types that we can reference as well?

**Comment by dougwilson** [comment]
Hi @leifcr, I'm going to close this pull request since I haven't heard back and I can't find the information online from searching. If you can provide the information, please let me know and I can always re-open the pull request, or you can make a new one :)

**Comment by leifcr** [comment]
@dougwilson I'll get back to you as soon as there is information on a webpage, as of now it's only visible on the computer where the software is installed.

**Comment by dougwilson** [comment]
Ok, thanks, @leifcr! I just re-opened the pull request in anticipation :)

**Comment by dougwilson** [comment]
Hi @leifcr, I'm going to re-close this PR since I haven't heard back. If you ever get the information, feel free to issue a new pull request :) !

**Pull request closed without merging**
