### PR TITLE
Mark all +xml types as compressible

### PR DESCRIPTION
**Pull request by rmzelle**
Partially addresses #114.

### CODE REVIEW

**Comment by rmzelle** [comment]
Done. Do you still wish to keep entries that now only have a "sources" property? E.g.:

```
  "application/atom+xml": {
    "sources": [
      "http://en.wikipedia.org/wiki/Atom_(standard)"
    ]
},
```

I guess it's still useful in providing a documentation link to the MIME type in question.

**Comment by dougwilson** [comment]
> Do you still wish to keep entries that now only have a "sources" property?

You can delete them. There is no purpose to them at that point. Without any data in the object, the source doesn't reference where the data came from. The purpose of the source is to reference where the data in the object came from.

**Comment by dougwilson** [comment]
For your example, we already have a list of source: https://github.com/jshttp/mime-db/blob/master/src/iana-types.json#L118-L124 all of which are more authoritative than Wikipedia.

**Comment by rmzelle** [comment]
Done. I also found two +json types that still had `"compressible": true`, so I deleted those as well.

**Comment by dougwilson** [comment]
Please move the jsom changes to a separate PR and I can merge this as just the XML changes.

**Comment by rmzelle** [comment]
Cleaned up.

**Pull request closed without merging**
