### PR TITLE
add apple iwork mime types

### PR DESCRIPTION
**Pull request by manichandra**

### CODE REVIEW

**Comment by MSAJJAN-EEOC** [comment]
Thank you. When can i expect this to be released ?

**Comment by dougwilson** [comment]
Done.

**Comment by MSAJJAN-EEOC** [comment]
can you please update mime-types repository as well to include mime-db 1.36.0

**Comment by dougwilson** [comment]
Sorry I didn't see your comment before I left. Released mime-types 2.1.20 just now.

**Pull request closed without merging**
